"""Prose of the report and of the rerun notes. 10_build_report.py fills the {{...}} markers with the
tables written to cache/ by the other steps. Numbers quoted in the prose were copied from those files
on 2026-10-08; if the pipeline is rerun, check them against the tables that follow each paragraph."""

REPORT = r'''# arXiv query design for the Reliability, DOE and SPM tracks

Analysis date: 2026-10-08. Frozen corpus: `data/frozen/v1/`. All numbers below come from files written by the numbered scripts in this directory (file names are given next to each table). This document is generated by `10_build_report.py` from the prose in `report_text.py`.

This report presents options and evidence. The choice of query for each track is the owner's.

## 1. Short version

**Recommended starting points (one per track), with the main trade-off.**

| track | recommended candidate | papers retrieved (current query) | silver in-scope papers kept | silver out-of-scope papers removed | journal-gold recall (current query) | on-topic share of newly retrieved papers, hand sample of 40 |
|---|---|---|---|---|---|---|
| Reliability | `R4_context_plus_specific_phrases` | 472 (704) | 268 of 316 (85%) | 349 of 381 (92%) | 29 of 42 (23 of 42) | 33 of 40 (82%, 95% CI 68 to 91%) |
| DOE | `D2_add_stat_title_vocab` | 1,377 (771) | 674 of 678 (99%) | 0 of 96 | 30 of 52 (9 of 52) | 32 of 40 (80%, 95% CI 65 to 90%) |
| SPM | `S3_names_plus_stat_monitoring_terms` | 340 (157) | 142 of 142 | 0 of 13 | 32 of 44 (23 of 44) | 31 of 40 (78%, 95% CI 62 to 88%) |

The queries are printed verbatim in section 6. Sources: `cache/score_reliability.csv`, `cache/score_exp_design.csv`, `cache/score_spc.csv`.

**Three findings that drive the recommendations.**

1. The arXiv API stems search terms. `ti:reliability` and `ti:reliable` return the identical set (205 results each inside stat.ME, `cache/arxiv_probes.csv`). 219 of the 376 out-of-scope reliability papers have the word "reliable" in the title, against 14 of 316 in-scope papers and 2 of 1,718 journal reliability titles (`cache/phrase_coverage_reliability.csv`). The noise in the reliability track is therefore mostly this one stem, and it cannot be removed with `ANDNOT ti:reliable` because that would also remove "reliability". Requiring an engineering term in the abstract is what separates the two senses.
2. The current DOE query matches the arXiv vocabulary ("experimental design" is in 429 of 674 in-scope arXiv titles) but not the journal vocabulary ("experimental design" is in 24 of 798 journal DOE titles; "split plot", "computer experiments", "factorial", "optimal design(s)" and "screening" are common in the journals and nearly absent from the current arXiv corpus). Only 9 of 52 journal DOE articles that have an arXiv version are retrieved by the current query.
3. For SPM, adding the phrase "process monitoring" without restriction is expensive. Of 40 hand-checked new papers it brings in, 11 were on topic. The phrase is also the name of a process-mining task ("predictive business process monitoring") and a generic engineering term. Adding the field names "statistical process control" and "statistical process monitoring" is cheap (55 new papers, 30 of 40 hand-checked on topic), and "process monitoring" becomes usable when restricted to stat.ME or stat.AP.

**What rests on what.**

- Verified by reading (analyst hand labels): the journal-gold sets (291 matched articles screened by arXiv title, unclear ones by abstract), the on-topic share of newly retrieved papers (612 arXiv papers labelled from the title plus the opening of the abstract), and the 80-article check of the journal topic labels.
- Rests on the existing gpt-5.2 silver flags: every "in scope kept" and "out of scope removed" count.
- Rests on the keyword stand-in rubric: the journal topic labels used for the vocabulary tables, and the column "keyword stand-in (all new)" in the scoring tables.
- Rests on gpt-6-luna: nothing. Only 12 journal articles were labelled before the API account ran out of credit (section 2).

## 2. What could not be done

- **Luna labelling.** The plan was to label all 5,614 journal articles and up to 150 newly retrieved papers per candidate with `gpt-6-luna`. The first test batch of 12 articles succeeded (`cache/journal_labels.csv`, `cache/token_usage.csv`: 11,872 input and 1,299 output tokens). After that the coordinator reported that the OpenAI account had no credit left (HTTP 429), so no further calls were made. The scripts are in place and resumable: `02_label_journal_articles.R` and `08_label_new_samples.R`. Once labels exist, `05_vocabulary.py luna`, `07_score_candidates.py` and `09_handcheck_agreement.py` pick them up.
- **Stand-in used instead.** Journal topic labels come from a transparent keyword rubric (`qd_rubric.py`). The precision of newly retrieved papers comes from hand labels by the analyst, with larger samples than originally asked (40 per candidate instead of 30, 612 papers in total).
- **Who the "hand" is.** The hand labels were made by the analysis agent (Claude), not by the owner or another human. For arXiv papers the agent read the title and the first 150 to 250 characters of the abstract, not the whole abstract and not the PDF. Labels were not blind to which candidate a paper came from.
- **The R package aRxiv is not installed**, so queries were run with a small Python client against `http://export.arxiv.org/api/query` (`qd_arxiv.py`). The app uses aRxiv; the recommended queries are long (up to 1,488 characters) and were not tested through that package.
- **Cost.** One labelling call of 12 items: 11,872 input tokens (about $0.001 at $0.10 per 1M) and 1,299 output tokens (the output price was not given to me). Projected input cost of the full Luna run at the observed 990 input tokens per item: about 6,770 items (5,602 journal articles plus 1,168 sampled arXiv papers), 6.7M tokens, about $0.67, plus roughly 0.7M output tokens. OpenAlex, Semantic Scholar and arXiv calls were free.

## 3. Data coverage

**Journal reference corpus (OpenAlex, publication years 2010 to 2026).** Source ids were resolved from the ISSN and the returned journal name was asserted to match. File: `cache/journal_coverage.csv`.

| journal | ISSN | OpenAlex source | works 2010 to 2026 | kept as research items | with abstract (100+ characters) | with keywords or topics | arXiv id in OpenAlex |
|---|---|---|---|---|---|---|---|
| Journal of Quality Technology | 0022-4065 | S166831694 | 702 | 600 | 548 | 593 | 15 |
| Technometrics | 0040-1706 | S985303 | 1,275 | 996 | 913 | 977 | 76 |
| Quality Engineering | 0898-2112 | S13624874 | 1,369 | 1,075 | 901 | 1,073 | 5 |
| Quality and Reliability Engineering International | 0748-8017 | S165633816 | 3,216 | 2,943 | 2,912 | 2,936 | 13 |
| all four | | | 6,562 | 5,614 | 5,274 (94%) | 5,579 | 109 |

"Kept" means OpenAlex type article or review and a title that does not start with an editorial marker (erratum, book review, editorial, and so on; the pattern is in `01_fetch_openalex.py`). The filter is imperfect. Some book reviews whose title is the book title remain; they fall in the "other" class. Abstract coverage is lowest for Quality Engineering (84%) and Journal of Quality Technology (91%); articles without an abstract are labelled from the title and keywords only.

**arXiv versions of journal articles (the gold pool).** OpenAlex alone links only 109 of the 5,614 articles to arXiv, so a second query-independent source was added: the Semantic Scholar batch endpoint, looked up by DOI (5,257 articles have a DOI). Together they give 294 candidate pairs (99 found by both, 185 by Semantic Scholar only, 10 by OpenAlex only). Each arXiv id was fetched from the arXiv API and the two titles compared; 291 pairs with a normalised title similarity of at least 0.60 were accepted (Technometrics 198, Journal of Quality Technology 41, Quality and Reliability Engineering International 37, Quality Engineering 15). The 3 rejected pairs look like genuine retitled papers, so the threshold is conservative. File: `cache/journal_arxiv_matches.csv`. No title search against arXiv was used, so the pool does not depend on any candidate query.

**Frozen arXiv corpus.** The factsheet files hold several versions of some papers. Everything here is counted at paper level (arXiv id without version, flag of the highest version). That gives 709 reliability papers (316 in scope, 381 out of scope, 12 without a flag), 775 DOE papers (678, 96, 1) and 157 SPM papers (142, 13, 2). These differ from the row counts quoted in the task (416 of 756, 99 of 837, 16 of 165) only because of the version duplicates. Five out-of-scope reliability papers and four in-scope DOE papers are in the factsheet but not in the metadata file and are not returned by the current query today; they appear as "removed" or "lost" for every candidate, including the current one.

## 4. Labelling rubric and how far to trust the labels

**Rubric.** The same three definitions are used everywhere. The full text sent to Luna is the constant `RUBRIC` in `00_common.R`. In short:

- Reliability: failure-time, lifetime and degradation modelling of engineered items, remaining useful life and prognostics, maintenance and inspection policies, warranty, accelerated tests and test plans, reliability growth, system, structural or software reliability, repairable systems, failure mode analysis, stress-strength, lifetime distributions framed for life testing. Not reliability of a measurement or rater, not reliability or calibration of machine-learning predictions, not "reliable" as an adjective, not degradation of images or model performance, not biomedical survival analysis without an engineering framing.
- DOE: construction, evaluation or analysis of designed experiments (factorial, screening, split-plot, mixture, optimal, space-filling, computer experiments, sequential or Bayesian design, online experiments), response surface methodology, robust parameter design, or applied studies whose central method is a designed experiment. Not papers that merely run experiments, not apparatus or lab setups, not "response surface" as a physical surface.
- SPM: control charts of any kind, Phase I and Phase II analysis, run-length properties, sequential change detection or surveillance framed as monitoring, process capability, monitoring-oriented fault detection in industrial processes. Not feedback control, not offline change-point estimation, not generic outlier detection.

**Keyword stand-in (`qd_rubric.py`).** A topic is assigned when the title or the keywords contain at least one term from that topic's list, or the abstract contains at least two distinct terms, unless a title-level exclusion matches. It labels 1,718 journal articles reliability, 798 DOE, 1,757 SPM and 1,643 none of the three (`cache/journal_labelled_kw.csv`; multiple labels allowed).

**Hand check of the journal labels.** A seeded random sample of 80 articles (20 per rubric-positive topic and 20 rubric-negative) was read (title and opening of the abstract). All three labels were judged for each article. Files: `hand_labels/journal_handcheck.csv`, `cache/handcheck_agreement.md`.

{{file:cache/handcheck_agreement.md}}

Reading: on journal articles the keyword rubric agreed with the hand label in 77, 74 and 78 of 80 cases for reliability, DOE and SPM. Its errors were over-inclusion (for example "Optimal Design of a CUSUM Chart" labelled DOE, a special-issue editorial labelled SPM) and a few misses (two DOE papers and one process-capability paper in the negative stratum). The sample is stratified, so these are not population accuracy figures. On arXiv papers the same rubric is much weaker (74 to 86% agreement with the hand labels, with errors in both directions), which is why the scoring tables report it only as a secondary column. The single Luna batch (12 articles) agreed with the keyword rubric on 35 of 36 labels; that is too small to say anything about Luna.

**Judgement calls in the hand labels** that a different reader might make differently:

- Reliability: papers proposing lifetime distributions (Weibull extensions and similar) were counted on topic when the abstract framed them for failure or life-test data, off topic when the framing was biomedical or generic. Rare-event and failure-probability simulation papers were counted on topic when framed as reliability analysis of engineering systems.
- DOE: clinical-trial designs (dose finding, stepped wedge) were counted on topic when the contribution was a design; A/B testing and online experiments were counted on topic; pure Gaussian-process emulation without a design component was excluded from the gold set but counted on topic in the new-paper samples when the paper was framed as a computer experiment.
- SPM: sequential and quickest change detection theory was counted on topic; offline change-point tests were not; neural-network fault detection for industrial processes was counted on topic; predictive business process monitoring was not.

## 5. How the arXiv API matches terms

Probes in `cache/arxiv_probes.csv` (run by `06_run_candidates.py`):

| query | results |
|---|---|
| `ti:reliability AND cat:stat.ME` | 205 |
| `ti:reliable AND cat:stat.ME` | 205 |
| `ti:"reliability analysis" AND cat:stat.ME` | 16 |
| `ti:"reliable analysis" AND cat:stat.ME` | 16 |
| `ti:"design of experiment"` | 173 |
| `ti:"design and experiments"` | 173 |
| `ti:"experimental design" AND cat:cs.HC` | 12 |
| `ti:"experience design" AND cat:cs.HC` | 9 |
| `(ti:"control chart" OR abs:"control chart")` | 157 |

Consequences. Terms are stemmed, so "reliability" also matches "reliable", "repairable" matches "repair", "prognostics" matches "prognostic" and "experiment" overlaps with "experience" (several out-of-scope DOE papers are user-experience design papers in cs.HC). Stopwords and punctuation inside a quoted phrase are ignored, so `ti:"design of experiment"` also returns robotics and physics papers titled "... Design and Experiments". Single ambiguous words therefore need either a second condition or a category restriction; multi-word technical phrases are much safer.

## 6. Candidate queries (verbatim)

All queries were run against `http://export.arxiv.org/api/query` on 2026-10-08, paged with `max_results=1000` and a pause of at least 3.2 seconds between calls. For every candidate the number of parsed records equals the `totalResults` reported by the API (`cache/candidate_sizes.csv`). The current queries return 704, 771 and 157 records, the same as the frozen metadata files.

Building blocks (defined in `qd_candidates.py`):

{{blocks}}

### Reliability

{{queries:reliability}}

### DOE

{{queries:exp_design}}

### SPM

{{queries:spc}}

How the candidates were arrived at. A first set was written from the vocabulary tables in the appendix. After the first round of hand labels three things were changed and the affected candidates re-sampled: (a) for reliability the journal-vocabulary block was narrowed to the phrases that were specific in the sample (`R_SPECIFIC`), because single words such as `ti:lifetime`, `ti:repairable`, `ti:prognostics` and the phrase `ti:"failure time"` pulled in customer lifetime value, "repair" in machine learning, biomedical prognostic models and accelerated failure time survival models; (b) for DOE `ti:"active learning"` was dropped (519 mostly machine-learning papers) and `ti:"orthogonal array"` and `ti:"computer experiments"` were moved inside the statistics categories; (c) for SPM the unrestricted `abs:CUSUM` was dropped (offline CUSUM change-point tests) and "process monitoring" was restricted to stat.ME or stat.AP. Because R4, S3 and S4 were tuned this way, their hand samples are partly but not fully independent of the tuning: 34 of 40 (R4), 23 of 40 (S3) and 31 of 40 (S4) sampled papers were labelled after the query was fixed. A last change added the title forms of nine context phrases to `R_ENG`; it changed only which frozen-corpus papers R2 to R5 keep (five more in scope, three more out of scope for R3 and R4), not the newly retrieved sets.

## 7. Scoring

Columns. "Retrieved" is the size of the result set. "Silver in scope kept" and "silver out of scope removed" compare with the frozen corpus and rest on the gpt-5.2 flags. "Gold recall" is the share of hand-labelled journal articles with an arXiv version that the query retrieves; it is independent of the current query and of the silver flags. "New papers" are retrieved papers not in the frozen corpus. "New on-topic, hand sample" is the analyst's label on a seeded random sample of 40 new papers per candidate, with a 95% Wilson interval. "Keyword stand-in" applies `qd_rubric.py` to all new papers and is shown for completeness; where it disagrees with the hand sample, trust the hand sample. "Est. overall precision" combines silver precision on the old part with the hand estimate on the new part, and "est. relevant papers" is the corresponding count; both inherit the sampling error of the hand estimate.

Gold sets (`hand_labels/gold_ids.json`, `cache/gold_*.csv`): 42 reliability articles (QREI 17, Technometrics 11, JQT 8, Quality Engineering 6), 52 DOE articles (Technometrics 29, JQT 14, QREI 6, Quality Engineering 3) and 44 SPM articles (Technometrics 16, JQT 14, QREI 10, Quality Engineering 4).

Each track section below has the scoring table, then for every candidate a random 15 of the in-scope papers it would lose and the first 15 (in seeded random order) of the papers it would gain, then the gold articles the current query misses. Full lists are in `cache/lost_*.csv` and `cache/gained_*.csv`. Paper titles are reproduced as they appear on arXiv.

{{file:cache/score_tables.md}}

## 8. Recommendation and risks

### Reliability: `R4_context_plus_specific_phrases`

Reason. It is the only candidate that improves both sides. Against the current query it removes 349 of 381 silver out-of-scope papers, keeps 268 of 316 silver in-scope papers, raises journal-gold recall from 23 to 29 of 42, and the 163 papers it adds were on topic in 33 of 40 hand-checked cases. Estimated overall precision moves from 0.46 to about 0.87, with an estimated 402 relevant papers against 316 today.

Alternatives. `R3_context_required` is the same query without the added phrases: the smallest change that fixes precision (309 papers, silver precision 0.89), but it retrieves no new papers and gold recall stays at 22 of 42. `R2_statML_needs_context` keeps 301 of 316 in-scope papers and is the choice if losing existing in-scope papers is unacceptable, at a silver precision of only 0.60, because "reliable" titles in stat.ME and stat.AP stay. `R5_broad` reaches 33 of 42 gold articles but only 17 of 40 sampled new papers were on topic.

Risks.

- 48 silver in-scope papers are lost (a random 15 are listed in section 7). Reading that list, a part of them are doubtful silver positives (machine-learning "reliability" papers and comment or rejoinder notes), but genuine losses remain, for example degradation and acceptance-sampling papers whose abstracts use none of the context terms. The context list `R_ENG` is the lever: adding terms recovers recall and costs precision.
- The "in scope" definition that produced the silver flags and my hand labels differ at the margins (lifetime distributions, rare-event simulation). The 82% figure would be lower under a stricter reading.
- 13 of 42 gold articles are still missed. Four are outside the five statistics categories (eess.SY, cs.SE, cs.DC). The others are statistics papers on recurrent events, time-to-failure, lifetime data or prognostics whose title and abstract do not use the query's terms.
- The categories remain stat.ME, stat.AP, stat.ML, stat.CO and stat.OT. Reliability work posted only in eess.SY or cs.LG is not retrieved by design. `R5_broad` shows the cost of opening that door with the present vocabulary.

### DOE: `D2_add_stat_title_vocab`

Reason. It keeps the whole current result set and adds the journal vocabulary. Gold recall rises from 9 to 30 of 52 and 32 of 40 sampled new papers were on topic. The result set grows from 771 to 1,377.

Alternatives. `D1_add_title_vocab` is the conservative step (166 new papers, gold recall 17 of 52). `D3_D2_minus_noisy_cats` additionally drops cs.HC, cs.RO and physics.ed-ph, removing 26 of 96 silver out-of-scope papers at the cost of 15 in-scope ones; its higher hand estimate (37 of 40) comes from an almost identical set of new papers (603 against 606), so the difference from D2 is sampling noise, not an effect of the exclusion. `D4_add_stat_abstracts` reaches 44 of 52 gold articles but adds 1,792 papers of which 24 of 40 sampled were on topic, many of them causal-inference and clinical-trial papers that mention an experimental design in passing.

Risks.

- Scope drift. D2 brings in optimal-design theory from math.ST, A/B testing and online experiments, and some clinical-trial design papers. I counted these on topic. If the owner wants an industrial-statistics DOE track only, the on-topic share of new papers is lower than 80%, and the phrases `ti:"A/B testing"`, `ti:"online experiments"` and `ti:"controlled experiments"` are the ones to drop.
- The 96 current out-of-scope papers all remain (12% of the corpus). They come from stemming and stopword behaviour on the existing title phrases ("Design and Experiments", "user experience design", "response surfaces" in physics). D3 is the only candidate that addresses this, bluntly.
- 606 new papers would need factsheet extraction.
- 22 of 52 gold articles are still missed, mostly sequential-design and active-learning papers for simulation experiments whose titles name Gaussian processes, surrogates or calibration and no design phrase from the query. D4 reaches most of them only by matching abstracts.

### SPM: `S3_names_plus_stat_monitoring_terms`

Reason. It answers the renaming question with the best balance found. It keeps all 157 current papers, adds the SPC and SPM field names anywhere, adds "process monitoring" only inside stat.ME or stat.AP, and adds a short list of monitoring terms inside statistics categories. Gold recall rises from 23 to 32 of 44 and 31 of 40 sampled new papers were on topic.

On the specific question asked. Adding `"statistical process control"` and `"statistical process monitoring"` (`S1`) captures 6 more gold articles (29 of 44) for 55 new papers, 30 of 40 sampled on topic. The off-topic ones use "statistical process control" as a borrowed idea in another field or mention it in passing. Adding unrestricted `"process monitoring"` (`S2`) adds one more gold article and 335 further papers; 11 of 40 sampled new papers were on topic, and estimated overall precision falls from 0.92 to about 0.46. Excluding process-mining vocabulary (`S2x`) removes 120 papers but the sampled share stays near 30% (12 of 40), because most remaining matches are engineering papers that use "process monitoring" for sensing or machine-learning work without a statistical monitoring method.

Alternative. `S4_plus_sequential_change_detection` adds sequential and quickest change detection inside statistics categories (472 papers, gold recall 33 of 44, 34 of 40 sampled on topic). Whether that theory-heavy literature (math.ST, often cross-listed in cs.IT) belongs in a track called Statistical Process Monitoring is a scope decision. I labelled it on topic, which is why S4 scores well.

Risks.

- The 78% estimate has a wide interval (62 to 88%) and 17 of the 40 sampled papers were labelled before the query was fixed.
- 12 of 44 gold articles are still missed, mainly monitoring and online change-point papers posted in stat.ML or cs.LG that never use chart vocabulary.
- `abs:EWMA` and `abs:"control limits"` are restricted to statistics categories because both terms occur in finance and control engineering.

### Risks common to all three

- **Small and uneven gold sets.** 42, 52 and 44 articles, with Technometrics and JQT over-represented because their authors post to arXiv more often than QREI and Quality Engineering authors. Gold recall describes the statistics-heavy end of each topic.
- **Sample size.** Each hand estimate is 40 papers. Differences of less than about 15 percentage points between candidates should not be read as real.
- **Single reader, shallow read.** Hand labels come from one AI reader using titles and abstract openings. Agreement with an independent labeller (Luna or a human) has not been measured.
- **Silver flags are not ground truth.** Some papers flagged in scope by gpt-5.2 look out of scope on title and abstract (several appear in the R3 and R4 "lost" lists), and the reverse will also occur.
- **Stemming is undocumented behaviour.** If arXiv changes how the API analyses terms, result sets will change. The probe queries in `06_run_candidates.py` can be rerun to detect that.
- **Operational cost.** Switching queries adds papers that need gpt-5.2 factsheet extraction (about 163 for R4, 606 for D2, 183 for S3) and, for reliability, raises the question of whether the 395 current papers that R4 no longer retrieves (48 in scope, 344 out of scope, 3 unflagged) should be removed from the displayed corpus or kept with their flags. Neither was costed here.
- **Query length.** R4 is 1,488 characters, D2 is 695 and S3 is 509. They run through a plain GET request; the R package aRxiv was not available to test.

## 9. How to rerun

See `README.md`. In order: `01` (OpenAlex), `03` (arXiv matching), `04` (keyword labels and hand-check sample), `05` (vocabulary), `06` (run candidates), `07` (score), `09` (agreement), `10` (this report). Steps `02` and `08` are the Luna labelling steps to run once the API account has credit.

## Appendix A. Distinguishing vocabulary and arXiv categories

Method (`05_vocabulary.py`). For each track three groups are compared: J, journal articles labelled on topic by the keyword rubric; I, arXiv papers in the frozen corpus flagged in scope; O, arXiv papers flagged out of scope. The statistic is the log-odds ratio of document frequency, (J plus I) against O, with a 0.5 pseudo-count, divided by its standard error (z). Terms are one to three words. Each table shows the 20 highest-ranked single words and the 20 highest-ranked phrases on one side. Document counts are given for all three groups so the reader can see which group drives a term.

Caveats. J was selected by a keyword rubric, so the rubric's own terms rank high on the in-scope side by construction; the I column (silver flags, independent of the rubric) is the check. Publisher boilerplate ("John Wiley Sons Ltd") appears in journal abstracts and should be ignored. For SPM the O group has only 13 papers, so the out-of-scope side is not informative; the phrase-coverage table is the useful one there.

The exact-phrase coverage tables answer a different question: how often a phrase that could go into a query appears in journal on-topic titles, in arXiv in-scope papers and in arXiv out-of-scope papers.

{{file:cache/vocab_tables.md}}
'''

README = r'''# Query design analysis (Reliability, DOE, SPM tracks)

Evidence for choosing new arXiv API queries for the QE ArXiv Watch tracks. Nothing here modifies the app.
The findings are in `REPORT.md`.

## Layout

- `01` to `10`: steps in run order (Python unless the name ends in `.R`).
- `qd_*.py`, `00_common.R`: shared code. `qd_candidates.py` holds the candidate queries, `qd_rubric.py` the
  keyword stand-in rubric, `00_common.R` the Luna rubric and the cached labeller.
- `hand_labels/`: the analyst's hand labels (inputs to steps 07 and 09; kept under version control).
- `cache/`: everything downloaded or derived (ignored by git). Raw API responses are cached, so a rerun
  makes no network calls unless a query changes or the cache is deleted.
- `report_text.py`: prose of the report; `10_build_report.py` merges it with the generated tables.

## Rerun

From this directory, in Git Bash:

```bash
python -I 01_fetch_openalex.py            # OpenAlex works for the four journals, 2010 to 2026
python -I 03_match_journal_to_arxiv.py    # arXiv versions via OpenAlex + Semantic Scholar (by DOI)
python -I 04_keyword_labels_journal.py    # keyword-rubric topic labels + 80-article hand-check sample
python -I 05_vocabulary.py                # vocabulary, phrase coverage, categories (add `luna` to use Luna labels)
python -I 06_run_candidates.py            # run every candidate against the arXiv API (3.2 s between calls)
python -I 07_score_candidates.py          # scoring tables, lost / gained lists, samples of new papers
python -I 09_handcheck_agreement.py       # agreement of automatic labels with the hand labels
python -I 10_build_report.py --write      # writes REPORT.md and README.md (without --write: prints the report)
```

Luna labelling (not run in October 2026 because the OpenAI account had no credit). Both scripts read
`OPENAI_API_KEY` from the repository `.env`, never print it, cache per item and can be rerun until complete:

```bash
"/c/Program Files/R/R-4.5.2/bin/Rscript.exe" --vanilla 02_label_journal_articles.R   # 5,614 journal articles
"/c/Program Files/R/R-4.5.2/bin/Rscript.exe" --vanilla 08_label_new_samples.R        # up to 150 new papers per candidate
python -I 05_vocabulary.py luna && python -I 07_score_candidates.py && python -I 09_handcheck_agreement.py
python -I 10_build_report.py --write
```

Token use is appended to `cache/token_usage.csv`. If the account still has no credit, ellmer waits and
retries on HTTP 429; stop the script and try again later.

## Changing a candidate

Edit `qd_candidates.py`, rerun `06` and `07`. If the set of newly retrieved papers changes, new papers
enter the hand sample: `python -I save_hand_labels.py <track> list` prints the unlabelled ones and
`python -I save_hand_labels.py <track> <0/1 string>` stores the labels. The prose in `report_text.py`
quotes numbers by hand, so update it after a rerun.
'''
