"""Prose of the follow-up part of the report (term-by-term analysis, eight journals, Luna v2 labels).
10_build_report.py fills the {{file:...}} markers with tables written to cache/ by steps 13 to 24.
Numbers quoted in the prose were copied from those files on 2026-10-08; after a rerun, check them
against the tables that follow each paragraph."""

FOLLOWUP = r'''# arXiv query design for the Reliability, DOE and SPM tracks

Part 1 is the follow-up analysis of 2026-10-08 (term-by-term tests, eight reference journals, gpt-6-luna labels). Part 2 is the first-round report, kept for the record; where the two disagree, Part 1 is the current evidence. This document is generated by `10_build_report.py` from `report_followup.py`, `report_text.py` and tables in `cache/`. The choice of query for each track is the owner's.

# Part 1. Follow-up: term-by-term analysis on eight journals

## 1.1 Short version

**Revised queries, assembled only from terms that passed a per-term test.** Sources: `cache/v2/score_*.csv`. Gold = journal articles with an arXiv version, labelled on topic by Luna and screened by the analyst (86 reliability, 74 DOE, 56 SPM). "On topic" for new papers is the Luna v2 label on a seeded random sample of 40.

| track | candidate | papers (current query) | gold recall (current) | silver in scope kept | silver out of scope removed | new papers on topic, n = 40 | request line through httr (limit 4,094) |
|---|---|---|---|---|---|---|---|
| Reliability | `R7_kept_terms_stat_only` | 655 (704) | 44 of 86 (29 of 86) | 269 of 316 | 349 of 381 | 29 of 40 | 3,174 |
| Reliability, broader | `R8_kept_terms_plus_clauses` | 2,332 (704) | 63 of 86 | 270 of 316 | 349 of 381 | 33 of 40 | 3,903 |
| DOE | `D5_kept_terms` | 2,022 (771) | 50 of 74 (10 of 74) | 674 of 678 | 0 of 96 | 32 of 40 | 1,482 |
| DOE, higher recall | `D7_kept_terms_plus_clauses` | 2,695 (771) | 68 of 74 | 676 of 678 | 0 of 96 | 25 of 40 | 2,468 |
| SPM | `S6_kept_terms` | 305 (157) | 44 of 56 (24 of 56) | 142 of 142 | 0 of 13 | 29 of 40, of which 8 also carry the change-detection-theory flag | 915 |
| SPM, theory excluded | `S7_kept_terms_strict` | 246 (157) | 37 of 56 | 142 of 142 | 0 of 13 | 26 of 40, none with the theory flag | 805 |

All queries are printed verbatim in section 1.8 and were run against the arXiv API.

**Main findings.**

1. *Bundles hide weak terms.* Tested one at a time under a stricter rubric, several terms of the first-round recommendations fail: for reliability `abs:"reliability analysis"` (11 of 25 sampled new papers on topic unrestricted, 14 of 25 inside the statistics categories), `abs:"degradation data"` (8 of 25), `ti:weibull` (4 of 25), `ti:"failure time"` (7 of 25); for DOE `ti:"computer experiments"` inside the statistics categories (12 of 25) and every abstract-level form of the current title phrases (`abs:"response surface"` 7 of 25, `abs:"experimental design"` 12 of 25 inside the statistics categories).
2. *Many terms do not match what they appear to.* The API stems words, drops a leading stopword and treats a stopword inside a phrase as a placeholder. `abs:"in-control"` is `abs:control` (238,603 against 238,814 results); `ti:"A-optimal"` is `ti:optimal` (79,414 against 79,446); `ti:"burn-in"` is `ti:burning` (692 each); `ti:repairable` is `ti:repair` (1,777 against 1,779); `ti:prognostics` is `ti:prognostic` (271 each); `abs:dependability` is `abs:depend` (402,817 each); `ti:"blocked design"` is `ti:"block design"`; `ti:"A/B testing"` is `ti:"B testing"` (114 each); `ti:"computer experiments"` is `ti:"computational experiments"` (129 each). `abs:"change-point"` does not match the one-word spelling "changepoint" (1,582 against 362). Section 1.4.
3. *The journals publish almost no sequential change-detection theory.* Of 13,780 articles in the eight journals I read 8 as quickest or sequential change-detection theory (ASMBI 4, QREI 3, CSDA 1; none in IISE or IIE Transactions, Technometrics, JQT, Quality Engineering or IEEE Transactions on Reliability), and none uses the vocabulary of e-detectors, e-processes, test martingales, conformal martingales or anytime-valid inference. They do publish sequential change detection *methods framed as monitoring* (20 found, 7 of them in Technometrics). Section 1.6.
4. *For SPM the scope decision moves the answer.* If theory-flagged papers count, `abs:"out-of-control"`, `abs:"control limits"`, `abs:EWMA` and `abs:Shewhart` (all inside the statistics categories) pass and the query reaches 44 of 56 gold articles. If they do not count, only the profile-monitoring terms pass and recall is 37 of 56. `abs:"average run length"`, `abs:"run length"`, `abs:CUSUM`, `abs:"change-point detection"` and the quickest-detection phrases fail either way as single terms.
5. *The R client imposes a hard length limit.* aRxiv 0.18 sends the query in a GET request line. The arXiv server rejects a request line over 4,094 bytes ("Request Line is too large (4402 > 4094)", HTTP 400), and httr percent-encodes more characters than a browser does. A first version of R8 (3,069 characters) failed for that reason; the assembly rule was tightened and the present R8 (2,649 characters, request line 3,903) is delivered, with about 190 bytes of headroom. Section 1.9.

**What rests on what.**

- gpt-6-luna with the v2 rubric: the topic labels of all 13,780 journal articles; the on-topic shares in every per-term, per-clause and per-candidate table (9,604 arXiv papers labelled).
- The analyst's reading: screening of the gold candidates (250 titles, 34 vetoed), the classification of change-detection articles in section 1.6, and two blind agreement checks (80 journal articles, 120 arXiv papers).
- gpt-5.2 silver flags (frozen corpus): "in scope kept", "out of scope removed" and the clause tests in section 1.5.
- Keyword rubric: nothing in Part 1 except its comparison with Luna in section 1.3.

## 1.2 Eight-journal reference corpus

OpenAlex sources were resolved by ISSN and the returned journal name asserted (`01_fetch_openalex.py`). IIE Transactions is the predecessor title of IISE Transactions and is a separate OpenAlex source (S63835026); its 2010 to 2016 articles are included. arXiv versions come from OpenAlex locations plus a Semantic Scholar lookup by DOI, checked by title similarity against arXiv metadata (1,077 candidate pairs, 1,068 accepted; `cache/journal_arxiv_matches.csv`). Where OpenAlex has no abstract the Semantic Scholar abstract is used, then the abstract of the matched arXiv version (`cache/journal_text.csv`). Topic counts are Luna v2 labels; an article can carry several. Source: `cache/journal_coverage_v2.csv`.

{{file:cache/journal_coverage_v2.md}}

Notes.

- *Computational Statistics & Data Analysis.* OpenAlex has abstracts for only 10% of its 3,275 research items (Elsevier). Semantic Scholar raises that to 42%; the other 1,894 articles were labelled from the title and OpenAlex keywords and topics. Luna labelled 69 reliability, 126 DOE and 23 SPM articles; only those enter the vocabulary and gold sets, and only 3, 12 and 1 of them have an arXiv version. Topic counts for this journal are probably undercounts.
- *IEEE Transactions on Reliability* has 77 DOE-labelled articles (1 with an arXiv version) and 23 SPM-labelled articles (none with an arXiv version). They are reported here and kept out of the DOE and SPM gold sets and vocabulary.
- *IISE Transactions* runs focus issues, including Quality and Reliability Engineering; OpenAlex does not record the focus issue, so the topic labels are the only split available (IISE and IIE together: 280 reliability, 77 DOE, 128 SPM).

**Expanded gold sets** (`18_build_gold_v2.py`, `hand_labels/gold_v2_review.json`, `hand_labels/gold_ids_v2.json`). Candidates are articles with an accepted arXiv version that Luna labelled on topic, plus the first-round hand gold. I screened every candidate by title, and by abstract where the title was not enough: reliability 101 candidates, 15 vetoed, 86 gold; DOE 93, 19 vetoed, 74 gold; SPM 56, none vetoed, 56 gold. For SPM the expansion adds 12 articles to the first-round 44: ASMBI 6, IISE Transactions 4, CSDA 1, and one Technometrics article accepted on Luna's label.

## 1.3 Rubric v2 and agreement

The v2 rubric (`00_rubric_v2.R`) defines each topic by what the reference journals publish: a label is TRUE only when the main contribution is framed around an engineered product, process, quality characteristic, engineered system or experiment. It excludes "reliable" machine learning, generic lifetime-distribution and survival work, clinical-trial designs, bandit theory, surrogate modelling without a design component, offline change-point analysis and process mining, and it carries a fourth label, CHANGE_THEORY, for sequential or quickest change-detection theory.

Agreement tables (`19_handcheck_v2.py`, `cache/v2/agreement_v2.md`). The hand samples were drawn stratified on the Luna label and shown to me shuffled and without the Luna labels.

{{file:cache/v2/agreement_v2.md}}

Reading.

- On journal articles Luna v2 and my blind labels agree on 79, 77 and 80 of 80 articles. The keyword rubric and Luna agree on 93 to 97% of all 13,780 articles; the keyword rubric over-labels reliability (691 articles it marks that Luna does not) and misses DOE (313 the other way).
- On arXiv papers Luna is more inclusive than my reading. Of the 20 papers per track that Luna labelled on topic I agreed with 15 (reliability), 12 (DOE) and 7 (SPM). Luna almost never rejected a paper I accepted (3, 0 and 0 cases). The on-topic shares in the tables below are therefore upper estimates; the ranking of terms is more trustworthy than the level.
- For SPM, 8 of the 13 disagreements are quickest or sequential change-detection theory papers to which Luna gave both SPM = TRUE and CHANGE_THEORY = TRUE. Not counting theory-flagged papers raises agreement from 27 to 34 of 40. That flag is not clean either: among sampled papers carrying both labels there are genuine chart papers (for example "Signed Sequential Rank CUSUMs", a gold article, and "Optimal Design of the Shiryaev-Roberts Chart"). The SPM tables therefore report both counts, and the truth lies between them.
- The app's own screen prompt was not used for these labels and was not edited.

## 1.4 Tokenisation and stemming traps

Every candidate term was checked two ways: the share of its matches that contain the term literally (column "literal share" in the per-term tables; a low value means the API matched something else), and explicit count probes (`17_token_probes.py`, `cache/token_probes.csv`). Equal counts mean the API does not distinguish the two spellings.

Terms that do not match what they appear to, and what to do about each:

| term as written | what the API matches | evidence | consequence |
|---|---|---|---|
| `abs:"in-control"` | `abs:control` | 238,603 and 238,814 results | unusable |
| `ti:"A-optimal"` | `ti:optimal` | 79,414 and 79,446 | unusable; `"D-optimal"` is safe (82), `"I-optimal"` is not (literal share 0.26, matches "I. Optimization") |
| `ti:"burn-in"` | `ti:burn`, `ti:burning` | 692 each; 681 of 692 titles are non-literal | unusable |
| `ti:repairable` | `ti:repair` | 1,777 and 1,779 | use the phrase `"repairable system"` (16) |
| `ti:prognostics` | `ti:prognostic` | 271 each | use `"prognostics and health management"` |
| `ti:censored` | `ti:censor`, `ti:censoring` | 832 and 833; includes "cosmic censor" | dropped |
| `abs:dependability` | `abs:depend`, `abs:dependence` | 402,817 each | unusable |
| `ti:reliability` and every phrase built on it | `ti:reliable ...` | "reliability analysis" and "reliable analysis" 134 each; "reliability estimation" literal share 0.06 in abstracts | needs the context requirement or a title-only phrase |
| `ti:degradation` | `ti:degrade`, `degraded`, `degrading` | 1,707 each | "degradation model" matches "degraded models" (literal share 0.32 in abstracts) |
| `ti:"accelerated test"` | "acceleration test", "accelerating tests" | 30 each, literal share 0.17 | keep only inside the statistics categories |
| `ti:"design of experiment"` | any stopword in the middle: "design and experiments", "design for experiments" | 173 each | source of the "Design and Experiments" robotics titles |
| `ti:"experimental design"` family | "experiment" and "experience" share a stem | `ti:experiment` and `ti:experience` 18,908 each; "design experiment" and "design experience" 29 each | source of user-experience design titles |
| `ti:"computer experiments"` | "computational experiments", "computing experience" | 129 each, literal share 0.58 (0.16 in abstracts) | dropped as a single term; kept in conjunctions |
| `ti:"blocked design"` | `ti:"block design"` | identical sets (79) | one of the two is enough |
| `ti:"A/B testing"`, `"A/B tests"` | `"B testing"`, `"B tests"` | 114 each; matches "B-tests" | kept, restricted where needed |
| `ti:"order-of-addition"` in abstracts | "order ... addition" with any stopword | abstract literal share 0.05 | title form only, or inside the statistics categories |
| `ti:"optimal design"` | "optimally designed", "optimization design" | 612 each | kept only inside the statistics categories |
| `ti:"choice experiments"` | "delayed choice experiment" (physics) | literal share 0.31 | kept only inside the statistics categories |
| `abs:"change-point"` | not the spelling "changepoint" | 1,582 against 362 | both spellings are needed where the term is used |
| `ti:"multi-fidelity"` | not "multifidelity" | 415 against 116 | same |
| `abs:"Phase II monitoring"` | 2 results; `abs:"Phase monitoring"` gives 22 | roman numerals are kept as tokens | harmless, adds nothing |
| `abs:"out-of-control"` | "out of control" (191); "out control" gives 41 | the stopword position must be filled | safe |
| `abs:EWMA`, `abs:CUSUM` | case-insensitive (81 and 380) | | safe |
| `http://export.arxiv.org/api/query` | answers HTTP 301 to the https address | `cache/url_length_probe.csv` | httr follows the redirect; each request costs two round trips |

Full probe table:

{{file:cache/token_probes.md}}

## 1.5 Context requirements and exclusion clauses, tested by what they remove

Each clause is judged on the frozen corpus against the silver flags (`16_clause_tests.py`).

{{file:cache/clause_tables.md}}

Reading.

- *Reliability.* The whole precision problem sits in one title word: `ti:reliability` matches 207 in-scope and 351 out-of-scope papers (silver precision 0.37), while `ti:degradation` is at 0.75, `ti:maintenance` at 0.88 and `ti:"remaining useful life"` at 1.0. Requiring a context term removes 328 of those 351 at a cost of 40 in-scope papers. The context list is dominated by `abs:failure` (134 in scope admitted). It is also the leakiest term: 15 of the 32 out-of-scope papers that survive the requirement come in through `abs:failure` alone, against 24 in-scope papers that only it admits. Deleting it is a defensible stricter option. Nine of the 34 context terms admit no paper that another term does not already admit and could be deleted to shorten the query. The stat.ML clause is no longer a problem once context is required: stat.ML-only papers go from 72 in scope and 189 out of scope to 57 and 17.
- *DOE.* `ti:"experimental design"` carries the track (488 in scope, silver precision 0.94). `ti:"designed experiment"` is the weakest phrase (17 in scope, 12 out of scope) because it stems to "design(ing) experiment(s)". No exclusion is cheap except `ANDNOT cat:physics.ed-ph` (0 in scope lost, 4 out of scope removed). `ANDNOT cat:cs.HC` loses 8 to remove 15; the first-round D3 exclusion loses 15 to remove 26; no abstract term tested removes more than 9 out-of-scope papers. The 96 out-of-scope papers are spread thinly over many categories, so the practical way to deal with them is the app's relevance flag, not the query.
- *SPM.* The process-mining exclusion removes 120 of the 371 "process monitoring" papers and none of the frozen in-scope ones, but restricting the phrase to stat.ME or stat.AP is simpler and keeps 15 of the 19 in-scope papers it matches.

## 1.6 Do the eight journals publish sequential or quickest change-detection theory?

Method (`24_change_theory_table.py`, `hand_labels/change_theory_review.csv`). I searched titles and abstracts of all 13,780 articles for the wording, took every article that Luna flagged CHANGE_THEORY (104), read the titles and abstract openings of both sets, and classified the relevant ones into three kinds. The Luna flag alone is not usable as a count: it also fires on ordinary CUSUM, GLR and SPRT chart papers.

{{file:cache/v2/change_theory.md}}

Facts for the owner.

- *Theory in the strict sense* (optimality, minimax or asymptotic results for stopping rules, or performance analysis posed as the quickest-detection problem, not framed around a process or quality characteristic): 8 articles in 17 years. ASMBI has 4 (three by the same group on the Shiryaev-Roberts and CUSUM procedures, one on a "disorder problem"), QREI 3 (two on performance criteria for sequential change detection, one relating two CUSUM formulations), CSDA 1 ("Optimal sequential detection by sparsity likelihood", 2024, the only one that states asymptotic lower bounds on detection delay). IISE and IIE Transactions, Technometrics, JQT, Quality Engineering and IEEE Transactions on Reliability have none.
- *E-detectors, e-processes, test martingales, conformal test martingales, anytime-valid inference, confidence sequences*: no article in any of the eight journals uses these terms in its title or abstract.
- *Sequential or online change detection methods framed as monitoring* (data streams, networks, sensors; evaluated by run length or detection delay): 20 found. Technometrics 7 (six of them published in 2022), QREI 5, IISE Transactions 3, ASMBI 2, CSDA 2, JQT 1. This list comes from the wording search and is not exhaustive.
- *Sequential tests for acceptance or reliability demonstration* (SPRT plans, start-up demonstration tests) are a separate, older line: 14 found, mostly IEEE Transactions on Reliability, QREI and Quality Engineering. They are not change detection.
- Caveat: 58% of CSDA articles have no abstract in the corpus, so for that journal the search is mostly on titles.

On arXiv the proportions are reversed. Among sampled new papers matched by `abs:"sequential change-point detection"` inside the statistics categories, Luna gave the SPM label to 8 of 25 and all 8 also carry the theory flag; for `abs:CUSUM` it is 5 of 25, all 5 theory-flagged; for `abs:"average run length"` 11 of 25, 7 theory-flagged (`cache/terms/spc_terms.csv`, columns `sample_on_topic` and `sample_on_topic_other_rule` of the strict run).

## 1.7 Per-term tables

Method (`13_term_fetch.py`, `14_term_tables.py`, generalised from the coordinator's `11_spm_term_marginals.py`). For each track a names-based base query is fixed. Every term is run through the API in the title and in the abstract. Four variants are reported: title, title inside the statistics categories, abstract, abstract inside the statistics categories. For each: papers matched; papers new beyond the base; gold articles recovered that the base misses; the on-topic share of a seeded random sample of up to 25 new papers (Luna v2); the dominant primary categories of the new papers; the literal share.

Verdict rule, applied mechanically. Keep a variant when at least 60% of its sample is on topic (with fewer than 8 sampled papers: at least 60% and either a gold article recovered or every sampled paper on topic) and the variant would add no more than 50 off-topic papers (new papers times one minus the on-topic share). An unrestricted variant that alone adds more than 1,000 papers is not sampled and is dropped as too broad. For an unrestricted variant the share is a stratified estimate: papers inside the statistics categories are judged from its own sample pooled with the restricted variant's sample, papers outside from its own sample. Assembly: for each term the broadest kept form is taken; forms are then added in order of gold recovered and on-topic share, and a form enters the query only if at that point it still adds at least 10 papers or one gold article.

Two thresholds were changed after seeing results, and I disclose them: the off-topic cap was first 40 and was raised to 50 so that `ti:"optimal design"` inside the statistics categories (218 new papers, 20 of 25 on topic, 9 gold articles) would not be dropped on volume alone; the minimum contribution was first 3 papers and was raised to 10 to bring the reliability query under the server's request-line limit.

### Reliability

Base: the current title words, with an engineering-context term required, inside stat.ME, stat.AP or stat.ML (the first-round R3). The terms tested are the phrases of the first-round R4, the remaining journal vocabulary, and further vocabulary from the journal tables.

{{file:cache/terms/reliability_terms.md}}

Assembly order and what each kept form adds:

{{file:cache/terms/reliability_assembly.md}}

Clauses aimed at the gold articles still missed (`22_missed_gold_terms.py`):

{{file:cache/v2/conj_reliability.md}}

### DOE

Base: the current query (five title phrases).

{{file:cache/terms/exp_design_terms.md}}

Assembly:

{{file:cache/terms/exp_design_assembly.md}}

Clauses aimed at the gold articles still missed:

{{file:cache/v2/conj_exp_design.md}}

### SPM

Base: the coordinator's names-based base ("control chart", the SPC and SPM names, and "process monitoring" inside stat.ME or stat.AP). The first table counts a paper on topic when Luna gives the SPM label; the column `other rule` in `cache/terms/spc_terms.csv` and the second table do not count papers that also carry the change-detection-theory flag.

{{file:cache/terms/spc_terms.md}}

The same terms when theory-flagged papers are not counted on topic:

{{file:cache/terms/spc_terms_strict.md}}

Assembly (theory-flagged papers counted):

{{file:cache/terms/spc_assembly.md}}

Assembly (theory-flagged papers not counted):

{{file:cache/terms/spc_assembly_strict.md}}

Clauses aimed at the gold articles still missed (single terms such as "change-point detection", "online monitoring", "data streams" and "real-time monitoring" fail alone, so they are tested as conjunctions with a monitoring anchor):

{{file:cache/v2/conj_spc.md}}

Comparison with the coordinator's per-term results. The two screens agree on what to drop: `"average run length"`, `"run length"`, CUSUM, `"false alarm rate"`, Hotelling and `"in-control"`. They differ on `"monitoring scheme"` (10 of 25 here against 20 of 30 with the app's screen), `"statistical monitoring"` and `"self-starting"` (kept by the sample rule here but they add fewer than 10 papers, so they are left out of the assembled query, as is `abs:"monitoring statistic"`), and this analysis adds `ti:"monitoring method"`, `ti:"profile monitoring"` and `ti:"time between events"`. The app's screen counts change-detection theory as in scope; the v2 rubric tries not to, and Luna only partly complies (section 1.3).

## 1.8 Revised queries and scoring

`20_score_v2.py`, `qd_candidates_v2.py`. Candidates per track: the current query; the first-round recommendation; the query assembled from the kept terms; a variant (all kept terms inside the statistics categories for reliability and DOE, the strict assembly for SPM); the kept-term query plus the clauses of section 1.7 that recover missed gold; and for SPM the coordinator's revised query verbatim. "New versus current" counts retrieved papers that are in neither the current result set nor the frozen corpus. The on-topic share is the Luna v2 label on a seeded random sample of 40 of those new papers; each candidate has its own sample, so differences of ten points between nested candidates are within sampling error. For SPM the next column gives how many of the on-topic papers also carry the theory flag. The last column is the length of the HTTP request line as the httr client builds it; the arXiv server's limit is 4,094.

{{file:cache/v2/score_v2.md}}

## 1.9 Can the R client send these queries?

aRxiv 0.18 (the version in `renv.lock`) calls `httr::GET("http://export.arxiv.org/api/query", query = list(search_query = ..., ...))`, so the query travels in the URL. Three checks were made.

1. Padded probes with Python (`21_url_length_probe.py`): a URL of 4,028 characters is answered normally; 4,508 characters and above return HTTP 400; 12,008 and above return HTTP 414.
2. Every candidate sent through httr itself, the way aRxiv does (`23_httr_get_check.R`, `cache/httr_get_check.csv`). All candidates in the table above return HTTP 200 with the expected totalResults. The earlier, longer version of R8 (3,069 query characters) returned HTTP 400 with the message "Request Line is too large (4402 > 4094)".
3. The same query is longer through httr than through Python or a browser, because httr percent-encodes spaces as `%20` and also encodes quotes, colons and parentheses: R8 is 2,649 characters as text, 3,330 in a Python URL and 3,903 in the httr request line.

Consequences. The limit is 4,094 bytes for the whole request line, which leaves roughly 2,750 characters of query text. R8 fits with about 190 bytes to spare; aRxiv adds `sortBy` and `sortOrder` parameters when asked to sort, which fit within that margin, but any further term added to R8 will not. R7, D5, D7, S6 and S7 are well inside. aRxiv could not be run here (it is not installed in this R library), so its exact request was reproduced with httr and not called. The http endpoint now redirects to https; httr follows the redirect.

{{file:cache/url_length_probe.md}}

## 1.10 Recommendations, gold still missed, and risks

### Reliability

`R7_kept_terms_stat_only` is the conservative choice: the first-round base (context required) plus the kept terms, all inside five statistics categories. 655 papers, 44 of 86 gold articles (current query: 29), 269 of 316 silver in-scope papers kept, 349 of 381 out-of-scope removed, 29 of 40 sampled new papers on topic.

`R8_kept_terms_plus_clauses` is the choice if the track should follow what IEEE Transactions on Reliability, QREI and IISE Transactions publish, which is largely outside the statistics categories: 2,332 papers, 63 of 86 gold, 33 of 40 sampled new papers on topic. It triples the corpus (2,021 papers to extract), sits close to the request-line limit, and its unrestricted title terms (`ti:"predictive maintenance"`, `abs:"useful life"`, `ti:"reliability analysis"`, `ti:"fault tree"`) bring in the cs.LG and eess.SY prognostics literature.

Gold still missed by R8 (23 of 86; listed in section 1.8). Thirteen are IEEE Transactions on Reliability articles, most of them from computer dependability and hardware reliability (cs.AR, cs.PF, cs.SE, cs.DC, cs.LO: storage systems, soft errors, fault injection, performability). Their wording is "dependability", "availability", "soft errors", "fault vulnerability". `abs:dependability` is unusable (it stems to "depend"); `(abs:"soft errors" AND abs:reliability)` was kept and recovers one. The rest are statistics papers whose text never uses a reliability phrase: recurrent-event models, Birnbaum-Saunders tests, image-based prognostics, accumulated damage, structure functions.

Risks specific to reliability. Both revised queries drop about 394 papers of the current corpus, 46 or 47 of them silver in scope. The 82% and 72% on-topic shares are Luna's; by my reading of the blind sample Luna accepts about one reliability paper in four that I would not.

### DOE

`D5_kept_terms`: the current query plus 13 unrestricted and 17 category-restricted term forms. 2,022 papers, 50 of 74 gold (current: 10), nothing lost from the current corpus, 32 of 40 sampled new papers on topic.

`D7_kept_terms_plus_clauses` adds conjunctions such as `(ti:"active learning" AND abs:surrogate)`, `(ti:"sequential design" AND abs:simulation)` and `(abs:"computer experiments" AND ti:design)`: 2,695 papers, 68 of 74 gold, 25 of 40 on topic in its sample.

Gold still missed by D7 (6 of 74): "Sequential Adaptive Design for Jump Regression Estimation" and "Profile Bayesian Optimization for Expensive Computer Experiments" (IISE Transactions), "Entropy-based adaptive design for contour finding and estimating reliability" (JQT), a utility-emulation paper (Technometrics), an e-commerce inventory-testing paper (ASMBI) and a constant-stress accelerated-life-test planning paper (QREI). Their wording is "adaptive design" and "Bayesian optimization", both tested and dropped as single terms (7 of 25 and, inside the statistics categories, 15 of 25 with about 270 off-topic additions).

Risks specific to DOE. Luna is the most inclusive here: of 20 arXiv papers it labelled DOE in the blind check I agreed with 12 (it accepted causal-inference and ANOVA papers and a Bayesian-optimisation paper). Read with that discount, the new-paper precision of D5 is nearer 50% than 80%. The 96 out-of-scope papers of the current corpus all remain. D5 is 2.6 times the current corpus (1,251 papers to extract).

### SPM

`S6_kept_terms` if sequential change detection papers that Luna labels SPM are acceptable in the track: 305 papers, 44 of 56 gold (current 24, the coordinator's revised query 41), 29 of 40 sampled new papers on topic of which 8 also carry the theory flag. It differs from the coordinator's revised query by dropping `"monitoring scheme"`, `"statistical monitoring"`, `"self-starting"` and `"Phase II monitoring"` and adding `ti:"monitoring method"`, `ti:"profile monitoring"` and `ti:"time between events"`.

`S7_kept_terms_strict` if they are not: 246 papers, 37 of 56 gold, 26 of 40 on topic, none theory-flagged. It is the base plus profile-monitoring terms only.

`S8_kept_terms_plus_clauses` reaches 48 of 56 gold with 342 papers, but only 21 of 40 of its sampled new papers were on topic; I do not recommend it on this evidence.

Gold still missed by S6 (12 of 56) and their wording. Six are online or sequential change detection or monitoring for high-dimensional or streaming data, five in Technometrics and one in JQT ("online monitoring", "data streams", "change-point detection", "real-time monitoring", "concept drift monitoring", "sequential change detection"; categories stat.ML, cs.LG, stat.ME). Two are monitoring papers listed only in cs.LG or eess.SY ("subspace monitoring", "cross-covariance monitoring"). One is a change-detection hypothesis test for a surface-finishing process (IISE Transactions). One is deep-learning fault detection (IISE Transactions). One has "control limits" in the title only (ASMBI). One is a quickest-detection comparison of CUSUM and Shiryaev-Roberts (the ASMBI article counted as theory in section 1.6). As single terms the wording fails (`abs:"change-point detection"` 2 of 25 inside the statistics categories, `abs:"online monitoring"` 8 of 25, `abs:"data streams"` 2 of 25, `abs:"real-time monitoring"` 2 of 25). As conjunctions some pass on small samples, for example `(ti:monitoring AND abs:"false alarm")` inside the statistics categories (9 of 13, of which 4 without the theory flag) and `(abs:"average run length" AND abs:chart)`; they are what S8 adds.

### Risks common to all three

- *Luna shares are relative.* Samples are 25 per term variant and 40 per candidate; Luna is more inclusive than my reading on arXiv papers (section 1.3). Use the tables to rank terms, not to promise a precision.
- *The verdict thresholds are mine* (60% on topic, at most 50 off-topic additions, at least 10 papers or one gold article). The per-term tables give the counts, so the owner can apply a different bar term by term.
- *Gold sets are skewed.* 1,068 of 13,780 articles have an arXiv version; Technometrics and CSDA authors post far more often than QREI, IEEE Transactions on Reliability or Quality Engineering authors.
- *Assembled queries are unions of many small terms.* Each passed alone; their joint precision was measured only through the 40-paper samples.
- *Stemming is undocumented behaviour* and can change. `17_token_probes.py` reruns the probes.
- *arXiv throttling.* During this work the API answered HTTP 429 in bursts; `qd_arxiv.py` now waits 4 seconds between calls and backs off for 45 seconds or more after a 429.
- *Corpus growth.* The revised queries add 148 (S6) to 2,021 (R8) papers that would each need a factsheet extraction.

## 1.11 What changed from the first round, what was not done, and cost

- The first-round recommendations (R4, D2, S3) are superseded as recommendations; they are scored again in section 1.8 against the expanded gold. The first-round hand labels used a looser reading (theory counted as SPM, clinical-trial designs counted as DOE) and are not used in Part 1.
- `08_label_new_samples.R` (Luna v1 on the first-round samples) was not run; it is superseded by `15_label_arxiv_samples.R`.
- Not done: hand labels for the 40-paper candidate samples (only the 120-paper blind check was read by me); a test through the aRxiv package itself; any edit to the app's prompts or scope texts.
- Cost of the follow-up, from `cache/token_usage.csv` at the prices in the app's `R/usage.R` (USD 0.10 per 1M input tokens, USD 0.50 per 1M output tokens): 13,780 journal articles, 15.9M input and 1.56M output tokens, USD 2.37; 9,604 arXiv papers, 11.3M input and 1.27M output tokens, USD 1.77. Total USD 4.14 against a cap of USD 8. No HTTP 429 with exhausted credit occurred. OpenAlex, Semantic Scholar and arXiv calls were free.

## 1.12 Appendix: vocabulary with Luna labels and eight journals

`05_vocabulary.py luna`. Same method as Appendix A of Part 2, with J now the Luna-labelled on-topic articles of the eight journals (IEEE Transactions on Reliability counted for reliability only).

{{file:cache/vocab_tables_luna.md}}

---

# Part 2. First-round report (2026-10-08, four journals, keyword stand-in and analyst hand labels)

The text and tables below are the first-round report. Its tables are the files written in the first round (`cache/score_tables.md`, `cache/vocab_tables.md`, `cache/handcheck_agreement.md`); steps 04, 05, 07 and 09 now read the eight-journal corpus, so rerunning them changes those tables and the numbers quoted in this part.

'''

README_V2 = r'''# Query design analysis (Reliability, DOE, SPM tracks)

Evidence for choosing new arXiv API queries for the QE ArXiv Watch tracks. Nothing here modifies the app.
The findings are in `REPORT.md` (Part 1: follow-up on eight journals with Luna labels; Part 2: first round).

## Layout

- `01` to `24`: steps (Python unless the name ends in `.R`). `11` and `12` are the coordinator's SPM term scripts.
- `qd_*.py`, `00_common.R`, `00_rubric_v2.R`: shared code. `qd_terms.py` holds the terms tested, `qd_candidates.py`
  the first-round candidates, `qd_candidates_v2.py` the follow-up candidates, `00_rubric_v2.R` the Luna v2 rubric.
- `hand_labels/`: the analyst's labels and reviews (kept under version control).
- `cache/`: everything downloaded or derived (ignored by git). Raw API responses are cached.
- `report_followup.py`, `report_text.py`: prose; `10_build_report.py` merges it with the generated tables.

## Rerun (follow-up pipeline)

From this directory, in Git Bash. `R` stands for `"/c/Program Files/R/R-4.5.2/bin/Rscript.exe" --vanilla`.
Luna steps read `OPENAI_API_KEY` from the repository `.env`, never print it, are resumable, run with
`max_active = 4`, and stop (without retrying) when most of a chunk is refused.

```bash
python -I 01_fetch_openalex.py             # eight journals (nine OpenAlex sources), 2010 to 2026
python -I 03_match_journal_to_arxiv.py     # arXiv versions and missing abstracts (OpenAlex + Semantic Scholar)
R 02_label_journal_articles.R              # Luna v2 labels for every journal article
python -I 18_build_gold_v2.py              # coverage table; gold candidates; gold after hand_labels/gold_v2_review.json
python -I 13_term_fetch.py                 # what the API returns for every term (slow: 4 s per call, backs off on 429)
python -I 14_term_tables.py sample         # samples of new papers per term variant
R 15_label_arxiv_samples.R                 # Luna v2 labels for every sample file found
python -I 14_term_tables.py                # per-term tables, verdicts, assembled queries
python -I 14_term_tables.py strict         # SPM again, not counting theory-flagged papers
python -I 22_missed_gold_terms.py sample   # clauses aimed at missed gold: fetch and sample
R 15_label_arxiv_samples.R
python -I 22_missed_gold_terms.py          # clause tables and final queries
python -I 20_score_v2.py sample            # fetch the candidates, sample their new papers
R 15_label_arxiv_samples.R
python -I 20_score_v2.py                   # scoring tables, missed gold
python -I 16_clause_tests.py               # context and exclusion clauses against the silver flags
python -I 17_token_probes.py               # tokenisation and stemming probes
python -I 19_handcheck_v2.py               # agreement tables (journal_sample / arxiv_sample modes draw the blind samples)
python -I 21_url_length_probe.py           # URL length probes
R 23_httr_get_check.R                      # every candidate through httr GET, as aRxiv sends it
python -I 24_change_theory_table.py        # change-detection theory in the journals
python -I 05_vocabulary.py luna            # vocabulary tables with Luna labels
python -I 10_build_report.py --write       # writes REPORT.md and README.md (without --write: prints the report)
```

First-round steps (`04`, `05` without argument, `06`, `07`, `09`) still run but now read the eight-journal corpus,
so their tables differ from the ones quoted in Part 2 of the report.

## Changing a term or a threshold

Terms: `qd_terms.py` (single terms) and the `CLAUSES` dictionary in `22_missed_gold_terms.py`. Thresholds:
`SAMPLE_N`, `MAX_OFF`, `MIN_ADD` and the 60% bar in `14_term_tables.py` and `22_missed_gold_terms.py`.
After a change rerun from `13` (new terms) or `14` (thresholds) down to `20`, then `23` to confirm the
assembled query still fits the 4,094-byte request line. The prose in `report_followup.py` quotes numbers by hand.
'''
